### ISSUE TITLE
Request to add Alternative dimensions for visualizations 

### ISSUE THREAD

**Issue by dave876** [viz-centric/flair-bi#453]
Hello,
I found Flair BI visualizations quite intuitive and user friendly,  I do like to request alternative dimensions feature added to bar charts. 

This prevents the need for creating multiple visualization on the build page and repetitive queries being fired to database.

User should be able to change the dimensions from the drop down in the visualization widget.

Regards,
Dave

**Comment by admin-vizcentric** [comment]
Hi @dave876 

Thanks for you suggestion we will check with product development teams and get them to add it to roadmap.

Thanks,
Vizcentric Team

**Comment by admin-vizcentric** [comment]
Hi @dave876,

We have released this feature in Flair BI v2.5.1 for the clustered vertical bar chart. Now user can set alternative dimension on the clustered vertical bar chart properties and once this is set, user can choose and apply dimensions through the tool-tip(refer attachment) on the x-axis dimension text.

We will be releasing these features for all bar charts, line charts, Doughnut & Pie in version 3.0 which is due to be released by the end of April

![7a67d6a3-02f9-4905-8715-06f5b25679a5](https://user-images.githubusercontent.com/47797163/77905007-ce904680-7285-11ea-9dda-fff555c2eb24.jpeg)

Thanks,
Vizcentric Team

**Comment by admin-vizcentric** [comment]
Hi @dave876 

We released this feature as requested. If any issues please let us know. 

Best Wishes, 
VizCentric Support team
