### ISSUE TITLE
OKTA configuration

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-bi#512]
Hi @admin-vizcentric,

We are planning to use OKTA with Flair-BI, but I couldn't find in the documentation about how to associate the OKTA group with Dashboards and also the level of permission like as ready only.

I found this link: https://github.com/viz-centric/flair-bi/wiki/Authentication

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz 

Authentication is handled through OKTA, authorisation on user getting access to Flair BI dashboards & views is controlled from within the application's Permission Management section. 

User Management - to grant Roles to the users
> https://github.com/viz-centric/flair-bi/wiki/Tutorial---Get-Started-with-VizCentric-Flair-BI#User-Management

Permissions Management - to issue access rights to the dashboards
> https://github.com/viz-centric/flair-bi/wiki/Tutorial---Get-Started-with-VizCentric-Flair-BI#Permissions-Management

Thanks,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi @fabiofilz,

Thank you for your response.

We would like to work with OKTA groups so I user will belong to many Groups/Roles and these groups will have the permissions based in flair-bi roles. Is there any way to associate this OKTA group/role to Flair-bi role? Will it be necessary to also create a user in Flair-bi or it will be automatically done by the process? 

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz 

OKTA acts as IDP and is only responsible for authentication. Authorisations are managed from the flair bi application.

The reason being that we have multiple dashboards and at a granular level each of these dashboards can have multiple views, this makes role-based access control easily managed from the Flair BI application permission management section. 

For users that are in OKTA no need to create a separate user account in Flair BI, it is automatically handled by the application by replicating the user on first time login.

Once you setup OKTA and add users to the application in OKTA console, user gets automatically added to the flair Bi application on their first login. When the user is created for the first time user will have `ROLE_USER` You have to go to user management and add appropriate role to the user. It's recommended that you always assign role instead of giving permission to the user directly.

Checkout this link on how to configure [OKTA](https://github.com/viz-centric/flair-bi/wiki/OKTA-Configuration) for flair bi application

Thanks,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi Team,

This ticket can be closed. It is working fine now.

Kind regards,
Fabio
